sudo: required
language: rust
rust:
  - nightly
addons:
  apt:
    packages:
      - libssl-dev
cache:
  directories:
    - $HOME/.cargo
before_install:
  - rustup toolchain install stable
  - rustup component add --toolchain stable rustfmt
before_cache:
  - cargo install cargo-tarpaulin
  - rm -rf $HOME/.cargo/registry
script:
  - cargo clean
  - cargo build
  - cargo test
  - cargo +stable fmt -- --check
after_success:
  - cargo tarpaulin --run-types Doctests Tests --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
